version: "3"

services:

  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis
    volumes:
      - ./components/redis/data:/data
      #redis config file
      - ./components/redis/config/redis.conf:/usr/local/redis/config/redis.conf
    environment:
      TZ: Asia/Shanghai
    restart: always
    sysctls:
      net.core.somaxconn: 1024
    command: redis-server --requirepass 123456 --appendonly yes

  server:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    container_name: server
    volumes:
      - ./logs:/server/logs
      - ./config:/server/config
    ports:
      - "8080:8080"
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "10"
